split HTTP_X_FORWARDED_FOR and use last ip address
Tutorfair/assegai pull request #13
Opened 2017-10-26 11:49 UTC by shaunick

[ELB sometimes sends several IP addresses and then spam-blocker etc gets confused](https://www.pivotaltracker.com/story/show/152309680)

2017-10-26 12:22 UTC, jadatkins requested changes

2017-10-26 12:22 UTC, jadatkins commented on src/assegai/Server.php
> +		$this->remote_addr = $this->arrayGet('HTTP_X_FORWARDED_FOR', $s) ?: explode(",", $this->arrayGet('REMOTE_ADDR', $s))[count($s['REMOTE_ADDR'])-1];
@shaunick sorry, no. it is the `HTTP_X_FORWARDED_FOR` header that you have to split and take the last one of. On production, `REMOTE_ADDR` will be the IP address of the load balancer.

What you want is something like
```php
$this->arrayGet('HTTP_X_FORWARDED_FOR', $s) ? explode(',', $this->arrayGet('HTTP_X_FORWARDED_FOR', $s))[-1] : $this->arrayGet('REMOTE_ADDR', $s);
```

After merging this, we will have to update composer. I will tell you what to do but try to remember.

2017-10-26 15:38 UTC, shaunick commented
@jadatkins I've now split HTTP_X_FORWARDED_FOR, not REMOTE_ADDR.

2017-10-27 10:27 UTC, jadatkins approved these changes

2017-10-27 10:28 UTC, merged